apiVersion: v1
data:
  buildkitd.toml: |
    debug = false
    [worker.containerd]
      namespace = "buildkit"
    [registry."http://gitea-http.gitea.svc.cluster.local:3000"]
      http = true
      insecure = true
kind: ConfigMap
metadata:
  name: buildkit
  namespace: guestbook
  