apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: tag-created-sensor
spec:
  dependencies:
    - name: tag-created
      eventSourceName: webhook
      eventName: tag-created
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: build-and-push-docker-image-
              spec:
                workflowTemplateRef:
                  name: build-and-push-docker-image
                arguments:
                  parameters:
                    - name: version
                      value: "{{(events.webhook.tag-created.body.ref).split('/').last}}"
                    - name: commit
                      value: "{{(events.webhook.tag-created.body.after)}}"
  template:
    serviceAccountName: argo-events-sa

