apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: tag-created-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
    container:
      env:
        - name: LOG_LEVEL
          value: debug
  dependencies:
    - name: tag-created
      eventSourceName: webhook
      eventName: tag-created
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: build-and-push-docker-image-
              spec:
                workflowTemplateRef:
                  name: build-and-push-docker-image
                arguments:
                  parameters:
                    - name: version
                      value: "v0.0.0"
                    - name: commit
                      value: "xxxxxxx"
          parameters:
            - src:
                dependencyName: tag-created
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: tag-created
                dataKey: body.sha
              dest: spec.arguments.parameters.1.value
