apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  template:
    container:
      env:
        - name: LOG_LEVEL
          value: debug
  # service:
  #   ports:
  #     - port: 14000
  #       targetPort: 14000
  webhook:
    tag-created:
      endpoint: /tag-created
      method: POST
      port: "14000"
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource
spec:
  ports:
    - port: 14000
      protocol: TCP
      name: tcp
      targetPort: 14000
  selector:
    # pods created from `EventSource` will have the label of `eventsource-name=eventsourcename` by default so we use this selector to select it
    eventsource-name: webhook
  type: ClusterIP