apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    tag-created:
      endpoint: /tag-created
      method: POST
      port: 12000
      url: /tag-created
      filter:
        event:
          type: push
          expr: "body.ref.startsWith('refs/tags/')"
          