apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ironman-ui-pr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: bruj0
        # The Github repository
        repo: argocd-poc
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
          - feature
      filters:
        - branchMatch: ".*-argocd"
      requeueAfterSeconds: 90
  template:
    metadata:
      name: 'ironman-pr-{{.branch_slug}}-{{.number}}'
    spec:
      destination: 
        namespace: 'ironman-pr-{{.branch_slug}}-{{.number}}'
        server: "https://kubernetes.default.svc"
      project: ironman-project
      source: 
        repoURL: "https://github.com/bruj0/argocd-poc.git"
        targetRevision: '{{.head_sha}}'
        path: ironman/helm
        helm:
          parameters:
            - name: "image.tag"
            #TODO: change to head_sha when its built by CI
              value: green
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
