services:
  cloud-provider:
    #build: .
    image: registry.k8s.io/cloud-provider-kind/cloud-controller-manager:v0.4.0
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
