kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: frontend-http
            port:
              number: {{ .Values.ingress.port}}
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: localhost
