apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ironman-app
  namespace: argocd
spec: 
  destination: 
    namespace: ironman-ns
    server: "https://kubernetes.default.svc"
  project: ironman-project
  source: 
    project: 
    repoURL: "https://github.com/bruj0/argocd-poc.git"
    targetRevision: master
    path: ironman/app 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
